---
rules:
  ignore:
    #- add_db_index
    #- add_underscores_to_large_numeric
    #- always_else_in_case
    #- ambiguous_first_argument
    #- assigned_but_unused_variable
    #- assignment_in_conditional
    #- avoid_copy_paste
    #- avoid_empty_rescue_block
    #- avoid_global_variable
    #- avoid_similar_code
    #- avoid_singleton_variable
    #- avoid_using_curly_braces_for_multi-line_blocks
    #- check_return_value_of_save
    #- don_t_use_parentheses_around_the_condition
    #- extra_blank_line_detected
    #- extra_blank_line_detected_at_body_beginning
    #- extra_blank_line_detected_at_body_end
    #- favor_if_unless_for_single_line
    #- improve_coverage_of_class
    #- improve_coverage_of_method
    #- improve_coverage_of_project
    #- indent_when_as_deep_as_case
    #- missing_class_documentation
    #- missing_method_documentation
    #- naming_convention_for_class
    #- naming_convention_for_method
    #- naming_convention_for_module
    #- no_for_loop
    #- no_instance_variable_in_partial
    #- no_params_in_view
    #- no_session_in_view
    #- omit_parentheses_when_no_args
    #- prefer_accolades_over_doend_for_single-line_blocks
    #- prefer_map_over_collect
    #- prefer_reduce_over_inject
    #- prefer_ruby_19_new_hash_syntax
    #- prefer_ruby_19_new_lambda_syntax
    - prefer_single_quoted_strings
    #- reduce_number_of_params
    #- refactor_complex_class
    #- refactor_complex_method
    #- remove_trailing_whitespace
    #- restrict_auto_generated_routes
    #- shadowing_outer_local_variable
    #- simplify_call_to_render
    #- simplify_call_to_render_partial
    #- space_between_curly_brace_and_pipe_missing
    #- space_inside_closing_curly_brace_missing
    #- space_inside_opening_curly_brace_missing
    #- space_inside_parentheses_detected
    #- space_inside_square_brackets_detected
    #- space_missing_after_colon
    #- space_missing_after_comma
    #- space_missing_after_hash_sign
    #- space_missing_after_semicolon
    #- space_missing_inside_closing_curly_brace
    #- space_missing_inside_opening_curly_brace
    #- space_missing_to_left_of_parentheses
    #- star_interpreted_as_argument_prefix
    #- surrounding_space_missing_for_accolade
    #- surrounding_space_missing_for_addition
    #- surrounding_space_missing_for_arrow
    #- surrounding_space_missing_for_assign
    #- surrounding_space_missing_for_divide
    #- surrounding_space_missing_for_equality
    #- surrounding_space_missing_for_greater_than
    #- surrounding_space_missing_for_incr
    #- surrounding_space_missing_for_minus
    #- surrounding_space_missing_for_multiplication
    #- surrounding_space_missing_for_not_equal
    #- surrounding_space_missing_for_t_square
    #- use_a_logger
    #- use_def_with_parentheses_when_there_are_arguments
    #- uses_spaces_instead_of_tabs
