language: ruby
bundler_args: --without development
rvm:
  2.2.0
services:
  - postgres
before_script:
  - psql -c 'create database lyrem_ipsum_test;' -U postgres
script:
  - bundle exec rake dev:generate_token
  - RAILS_ENV=test bundle exec rake db:migrate db:test:prepare
  - bundle exec rake travis
