development:
  adapter: postgresql
  encoding: unicode
  database: lyrem_ipsum_dev
  pool: 5
  #username: postgres
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: lyrem_ipsum_test
  pool: 5
  #username: postgres
  password:
